# Official docker image.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

stages:
  - build

build-mas-py2:
  stage: build
  script:
    - docker build -t "$docker_user/erpnext-docker-debian:mas-py2-latest"
      --build-arg pythonVersion=python
      --build-arg appBranch=master
      .
    - docker push "$docker_user/erpnext-docker-debian:mas-py2-latest"
