# Official docker image.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

variables:
  docker_image: "pipech/erpnext-docker-debian"

stages:
  - build

build-mas-py2:
  stage: build
  variables:
    docker_image_tag: "mas-py2-latest"
  script:
    - docker info
    - docker build -t $docker_image:$docker_image_tag
      --build-arg pythonVersion=python
      --build-arg appBranch=master
      .
    - docker push $docker_image:$docker_image_tag
