# Official docker image.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

before_script:
  - docker login -u "$dh_user" -p "$dh_pass"

stages:
  - build

build-mas-py2:
  stage: build
  script:
    - docker build -t "$dh_user/erpnext-docker-debian:mas-py2-latest"
      --build-arg pythonVersion=python
      --build-arg appBranch=master
      .
    - docker push "$dh_user/erpnext-docker-debian:mas-py2-latest"
